name: card-system

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    hostname: ${KEYCLOAK_HOST:-keycloak}
    ports:
      - ${KEYCLOAK_ADMIN_PORT:-8081}:8080
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    networks:
      - card-system
 
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: ${RABBITMQ_HOST:-rabbitmq}
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - ${RABBITMQ_SERVER_PORT:-5672}:5672
      - ${RABBITMQ_ADMIN_PORT:-15672}:15672
    networks:
      - card-system

  discovery-server:
    image: gabrielluciano/card-system-discovery-server:1.0
    hostname: ${EUREKA_HOST:-discovery-server}
    ports:
      - ${EUREKA_ADMIN_PORT:-8761}:8761
    environment:
      - EUREKA_USERNAME=${EUREKA_USERNAME}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD}
    networks:
      - card-system

  customer-api:
    image: gabrielluciano/card-system-customer-api:1.0
    environment:
      - EUREKA_HOST=${EUREKA_HOST:-discovery-server}
      - EUREKA_USERNAME=${EUREKA_USERNAME}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD}
    networks:
      - card-system
    depends_on:
      - discovery-server

  card-api:
    image: gabrielluciano/card-system-card-api:1.0
    environment:
      - EUREKA_HOST=${EUREKA_HOST:-discovery-server}
      - EUREKA_USERNAME=${EUREKA_USERNAME}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    networks:
      - card-system
    depends_on:
      - discovery-server
      - rabbitmq

  credit-assessment-api:
    image: gabrielluciano/card-system-credit-assessment-api:1.0
    environment:
      - EUREKA_HOST=${EUREKA_HOST:-discovery-server}
      - EUREKA_USERNAME=${EUREKA_USERNAME}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    networks:
      - card-system
    depends_on:
      - discovery-server
      - rabbitmq

  api-gateway:
    image: gabrielluciano/card-system-api-gateway:1.0
    ports:
      - 8080:8080
    environment:
      - EUREKA_HOST=${EUREKA_HOST:-discovery-server}
      - EUREKA_USERNAME=${EUREKA_USERNAME}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD}
      - KEYCLOAK_HOST=${KEYCLOAK_HOST:-keycloak}
      - KEYCLOAK_PORT=8080
    networks:
      - card-system
    depends_on:
      - discovery-server
      - keycloak

networks:
  card-system:
    driver: bridge
