spring:
  application:
    name: customer-api

server:
  port: 0 # random port

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME:user}:${EUREKA_PASSWORD:password}@${EUREKA_HOST:localhost}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log
