spring:
  application:
    name: customer-api

server:
  port: 0 # random port

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://discovery-server-user:ZGlzY292ZXJ5LXNlcnZlci11c2Vy@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log
