spring:
  application:
    name: discovery-server

security:
  user:
    username: discovery-server-user
    password: ZGlzY292ZXJ5LXNlcnZlci11c2Vy

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-server-user:ZGlzY292ZXJ5LXNlcnZlci11c2Vy@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log
