spring:
  application:
    name: discovery-server

security:
  user:
    username: ${EUREKA_USERNAME}
    password: ${EUREKA_PASSWORD}

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${security.user.username}:${security.user.password}@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log
